package com.fortytwotalents.speakercardsgenerator.service;

import com.fortytwotalents.speakercardsgenerator.model.Speaker;
import com.fortytwotalents.speakercardsgenerator.model.Talk;
import com.fortytwotalents.speakercardsgenerator.repository.SpeakerRepository;
import com.fortytwotalents.speakercardsgenerator.repository.TalkRepository;
import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.util.List;
import java.util.UUID;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Service for generating speaker and talk banner images in bulk.
 *
 * <p>
 * Each banner is generated by calling the banner PNG endpoints on the running application
 * server (e.g. {@code /speaker-banner/{id}.png}). The resulting bytes can optionally be
 * saved to an output directory.
 */
@Service
public class BannerGenerationService {

	private static final Logger log = LoggerFactory.getLogger(BannerGenerationService.class);

	private final SpeakerRepository speakerRepository;

	private final TalkRepository talkRepository;

	@Value("${server.port:8080}")
	private int serverPort;

	@Value("${server.address:localhost}")
	private String serverHost;

	private final HttpClient httpClient = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(30)).build();

	public BannerGenerationService(SpeakerRepository speakerRepository, TalkRepository talkRepository) {
		this.speakerRepository = speakerRepository;
		this.talkRepository = talkRepository;
	}

	@Transactional(readOnly = true)
	public BannerGenerationResult generateAllSpeakerBanners() {
		List<Speaker> speakers = speakerRepository.findAll();
		log.atInfo().addArgument(() -> speakers.size()).log("Starting banner generation for {} speakers");

		BannerGenerationResult result = new BannerGenerationResult();
		for (Speaker speaker : speakers) {
			try {
				byte[] data = fetchSpeakerBannerPng(speaker.id);
				result.addSuccess(speaker.id, speaker.toString(), data.length);
				log.info("Generated banner for {} ({})", speaker, speaker.id);
			}
			catch (Exception e) {
				result.addFailure(speaker.id, speaker.toString(), e.getMessage());
				log.error("Failed to generate banner for {} ({})", speaker, speaker.id, e);
			}
		}
		return result;
	}

	/**
	 * Generates banners for the given speaker IDs only.
	 * @param speakerIds list of speaker UUIDs to process
	 * @return aggregated result
	 */
	@Transactional(readOnly = true)
	public BannerGenerationResult generateSpeakerBanners(List<UUID> speakerIds) {
		log.atInfo().addArgument(() -> speakerIds.size()).log("Starting banner generation for {} specific speakers");
		BannerGenerationResult result = new BannerGenerationResult();
		for (UUID id : speakerIds) {
			Speaker speaker = speakerRepository.findById(id).orElse(null);
			if (speaker == null) {
				result.addFailure(id, "Unknown", "Speaker not found");
				continue;
			}
			try {
				byte[] data = fetchSpeakerBannerPng(speaker.id);
				result.addSuccess(speaker.id, speaker.toString(), data.length);
			}
			catch (Exception e) {
				result.addFailure(speaker.id, speaker.toString(), e.getMessage());
				log.error("Failed to generate banner for {} ({})", speaker, speaker.id, e);
			}
		}
		return result;
	}

	/**
	 * Generates all banner types (speaker, talk, social) and saves each file to the given
	 * output directory.
	 *
	 * <p>
	 * Output layout:
	 *
	 * <pre>
	 * {outputDirectory}/
	 *   speaker/   ← {speakerId}.png
	 *   talks/     ← {talkId}.png
	 *   social/    ← {lastName}_{firstName}.png
	 * </pre>
	 * @param outputDirectory path to the directory where files will be written
	 * @return aggregated result with file paths
	 */
	@Transactional(readOnly = true)
	public BannerGenerationResult generateAllBanners(String outputDirectory) {
		List<Speaker> speakers = speakerRepository.findAll();
		List<Talk> talks = talkRepository.findAll();
		log.atInfo()
			.addArgument(() -> speakers.size())
			.addArgument(() -> talks.size())
			.addArgument(outputDirectory)
			.log("Starting banner generation for {} speakers and {} talks to {}");

		Path speakerDir = Path.of(outputDirectory, "speaker");
		Path talksDir = Path.of(outputDirectory, "talks");
		Path socialDir = Path.of(outputDirectory, "social");

		try {
			Files.createDirectories(speakerDir);
			Files.createDirectories(talksDir);
			Files.createDirectories(socialDir);
		}
		catch (IOException e) {
			throw new RuntimeException("Failed to create output directories: " + outputDirectory, e);
		}

		BannerGenerationResult result = new BannerGenerationResult();

		// Speaker banners
		for (Speaker speaker : speakers) {
			try {
				byte[] data = fetchSpeakerBannerPng(speaker.id);
				Path file = speakerDir.resolve(speaker.id + ".png");
				Files.write(file, data);
				result.addSuccess(speaker.id, speaker.toString(), data.length);
				result.addSavedFile(file.toString());
				log.info("Saved speaker banner for {} to {}", speaker, file);
			}
			catch (Exception e) {
				result.addFailure(speaker.id, speaker.toString(), e.getMessage());
				log.error("Failed speaker banner for {} ({})", speaker, speaker.id, e);
			}
		}

		// Talk banners
		for (Talk talk : talks) {
			try {
				byte[] data = fetchTalkBannerPng(talk.id);
				Path file = talksDir.resolve(talk.id + ".png");
				Files.write(file, data);
				result.addSuccess(null, talk.title, data.length);
				result.addSavedFile(file.toString());
				log.info("Saved talk banner for '{}' to {}", talk.title, file);
			}
			catch (Exception e) {
				result.addFailure(null, talk.title, e.getMessage());
				log.error("Failed talk banner for '{}' ({})", talk.title, talk.id, e);
			}
		}

		// Social banners
		for (Speaker speaker : speakers) {
			try {
				byte[] data = fetchSpeakerSocialPng(speaker.id);
				String filename = sanitize(speaker.lastName) + "_" + sanitize(speaker.firstName) + ".png";
				Path file = socialDir.resolve(filename);
				Files.write(file, data);
				result.addSuccess(speaker.id, speaker.toString(), data.length);
				result.addSavedFile(file.toString());
				log.info("Saved social banner for {} to {}", speaker, file);
			}
			catch (Exception e) {
				result.addFailure(speaker.id, speaker.toString(), e.getMessage());
				log.error("Failed social banner for {} ({})", speaker, speaker.id, e);
			}
		}

		log.info("Banner generation completed: {} successful, {} failed", result.getSuccessCount(),
				result.getFailureCount());
		return result;
	}

	private byte[] fetchSpeakerBannerPng(UUID id) throws Exception {
		return fetch("http://%s:%d/speaker-banner/%s.png".formatted(serverHost, serverPort, id));
	}

	private byte[] fetchTalkBannerPng(Long id) throws Exception {
		return fetch("http://%s:%d/talk-banner/%d.png".formatted(serverHost, serverPort, id));
	}

	private byte[] fetchSpeakerSocialPng(UUID id) throws Exception {
		return fetch("http://%s:%d/speaker-social/%s.png".formatted(serverHost, serverPort, id));
	}

	private byte[] fetch(String url) throws Exception {
		HttpRequest request = HttpRequest.newBuilder()
			.uri(URI.create(url))
			.timeout(Duration.ofSeconds(30))
			.GET()
			.build();
		HttpResponse<byte[]> response = httpClient.send(request, HttpResponse.BodyHandlers.ofByteArray());
		if (response.statusCode() != 200) {
			throw new RuntimeException("HTTP " + response.statusCode() + " for " + url);
		}
		return response.body();
	}

	/**
	 * Removes characters that are unsafe for file system paths.
	 * @param value input; may be {@code null}
	 * @return sanitised string, or {@code "unknown"} if the input is blank
	 */
	private static String sanitize(String value) {
		if (value == null || value.isBlank()) {
			return "unknown";
		}
		return value.replaceAll("[^a-zA-Z0-9._-]", "_");
	}

}
